### ISSUE TITLE
Recursion Depth

### ISSUE THREAD

**Issue by WurmPeter** [krzjoa/path.chain#1]
Hello,

You wrote a nice package, thanks. I would use it to compose paths.

Having directories with thousands of subdirectories and files, the generated config file gets far too big. Is there a way to only store the structure x levels deep? And/or without files?

**Comment by krzjoa** [comment]
Hi @Nefcairon,

At the moment there isn't, but I can see the `path_chain` function can be easily adopted to include this feature.

Please add a PR, which changes [this fragment of code](https://github.com/krzjoa/path.chain/blob/1f376a989e3b9679379815f8c45740476e64600d/R/path-chain.R#L103). You should replace `list.files` with a function, which allows to specify the maximum recursion depth. I think the [dirdf](https://github.com/HenrikBengtsson/dirdf/blob/master/R/dir2.R) package with its `dir2` function should be a good solution. You could only copy-paste that function with adding a relevant comment.

**Comment by WurmPeter** [comment]
Thanks, I'll give it a try.
